spring:
  r2dbc:
    pool:
      max-size: 20
      initial-size: 10
      validation-query: SELECT 1;
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
server:
  reactive:
    session:
      timeout: 30m
  error:
    include-message: always
  port: 8000
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        webflux: DEBUG
    reactor:
      core: DEBUG
      netty: DEBUG
application:
  contract:
    delay: 1
    timeout: 30
services:
  auth:
    hostname: http://localhost:8080
    resources:
      heartbeat: /public/heartbeat
